version: "3"
services:
    domain-health-checker:
        image: python:3.11.11-slim
        container_name: domain-health-checker
        volumes:
            # Mount the application code
            - ./:/app
            # Create a separate volume for results
            - ./results:/app/results
        working_dir: /app
        command: >
            bash -c "pip install --no-cache-dir -r requirements.txt && 
            echo 'Running Domain Health Checker...' && 
            python main.py"
        env_file:
            - .env
